<a href="https://colab.research.google.com/github/Shriansh16/Basic_deep_learning_projects/blob/main/ANN%20REVISION.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!unzip '/content/archive (19).zip'

Archive:  /content/archive (19).zip
  inflating: Churn_Modelling.csv

In [2]:
!pip install tensorflow

Requirement already satisfied: tensorflow in /usr/local/lib/python3.10/dist-packages (2.15.0)
Requirement already satisfied: absl-py>=1.0.0 in /usr/local/lib/python3.10/dist-packages (from tensorflow) (1.4.0)
Requirement already satisfied: astunparse>=1.6.0 in /usr/local/lib/python3.10/dist-packages (from tensorflow) (1.6.3)
Requirement already satisfied: flatbuffers>=23.5.26 in /usr/local/lib/python3.10/dist-packages (from tensorflow) (23.5.26)
Requirement already satisfied: gast!=0.5.0,!=0.5.1,!=0.5.2,>=0.2.1 in /usr/local/lib/python3.10/dist-packages (from tensorflow) (0.5.4)
Requirement already satisfied: google-pasta>=0.1.1 in /usr/local/lib/python3.10/dist-packages (from tensorflow) (0.2.0)
Requirement already satisfied: h5py>=2.9.0 in /usr/local/lib/python3.10/dist-packages (from tensorflow) (3.9.0)
Requirement already satisfied: libclang>=13.0.0 in /usr/local/lib/python3.10/dist-packages (from tensorflow) (16.0.6)
Requirement already satisfied: ml-dtypes~=0.2.0 in /usr/local/lib/python3.10/dist-packages (from tensorflow) (0.2.0)
Requirement already satisfied: numpy<2.0.0,>=1.23.5 in /usr/local/lib/python3.10/dist-packages (from tensorflow) (1.25.2)
Requirement already satisfied: opt-einsum>=2.3.2 in /usr/local/lib/python3.10/dist-packages (from tensorflow) (3.3.0)
Requirement already satisfied: packaging in /usr/local/lib/python3.10/dist-packages (from tensorflow) (23.2)
Requirement already satisfied: protobuf!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<5.0.0dev,>=3.20.3 in /usr/local/lib/python3.10/dist-packages (from tensorflow) (3.20.3)
Requirement already satisfied: setuptools in /usr/local/lib/python3.10/dist-packages (from tensorflow) (67.7.2)
Requirement already satisfied: six>=1.12.0 in /usr/local/lib/python3.10/dist-packages (from tensorflow) (1.16.0)
Requirement already satisfied: termcolor>=1.1.0 in /usr/local/lib/python3.10/dist-packages (from tensorflow) (2.4.0)
Requirement already satisfied: typing-extensions>=3.6.6 in /usr/local/lib/python3.10/dist-packages (from tensorflow) (4.9.0)
Requirement already satisfied: wrapt<1.15,>=1.11.0 in /usr/local/lib/python3.10/dist-packages (from tensorflow) (1.14.1)
Requirement already satisfied: tensorflow-io-gcs-filesystem>=0.23.1 in /usr/local/lib/python3.10/dist-packages (from tensorflow) (0.36.0)
Requirement already satisfied: grpcio<2.0,>=1.24.3 in /usr/local/lib/python3.10/dist-packages (from tensorflow) (1.60.1)
Requirement already satisfied: tensorboard<2.16,>=2.15 in /usr/local/lib/python3.10/dist-packages (from tensorflow) (2.15.2)
Requirement already satisfied: tensorflow-estimator<2.16,>=2.15.0 in /usr/local/lib/python3.10/dist-packages (from tensorflow) (2.15.0)
Requirement already satisfied: keras<2.16,>=2.15.0 in /usr/local/lib/python3.10/dist-packages (from tensorflow) (2.15.0)
Requirement already satisfied: wheel<1.0,>=0.23.0 in /usr/local/lib/python3.10/dist-packages (from astunparse>=1.6.0->tensorflow) (0.42.0)
Requirement already satisfied: google-auth<3,>=1.6.3 in /usr/local/lib/python3.10/dist-packages (from tensorboard<2.16,>=2.15->tensorflow) (2.27.0)
Requirement already satisfied: google-auth-oauthlib<2,>=0.5 in /usr/local/lib/python3.10/dist-packages (from tensorboard<2.16,>=2.15->tensorflow) (1.2.0)
Requirement already satisfied: markdown>=2.6.8 in /usr/local/lib/python3.10/dist-packages (from tensorboard<2.16,>=2.15->tensorflow) (3.5.2)
Requirement already satisfied: requests<3,>=2.21.0 in /usr/local/lib/python3.10/dist-packages (from tensorboard<2.16,>=2.15->tensorflow) (2.31.0)
Requirement already satisfied: tensorboard-data-server<0.8.0,>=0.7.0 in /usr/local/lib/python3.10/dist-packages (from tensorboard<2.16,>=2.15->tensorflow) (0.7.2)
Requirement already satisfied: werkzeug>=1.0.1 in /usr/local/lib/python3.10/dist-packages (from tensorboard<2.16,>=2.15->tensorflow) (3.0.1)
Requirement already satisfied: cachetools<6.0,>=2.0.0 in /usr/local/lib/python3.10/dist-packages (from google-auth<3,>=1.6.3->tensorboard<2.16,>=2.15->tensorflow) (5.3.2)
Requirement already satisfied: pyasn1-modules>=0.2.1 in /usr/local/lib/python3.10/dist-packages (from google-auth<3,>=1.6.3->tensorboard<2.16,>=2.15->tensorflow) (0.3.0)
Requirement already satisfied: rsa<5,>=3.1.4 in /usr/local/lib/python3.10/dist-packages (from google-auth<3,>=1.6.3->tensorboard<2.16,>=2.15->tensorflow) (4.9)
Requirement already satisfied: requests-oauthlib>=0.7.0 in /usr/local/lib/python3.10/dist-packages (from google-auth-oauthlib<2,>=0.5->tensorboard<2.16,>=2.15->tensorflow) (1.3.1)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.10/dist-packages (from requests<3,>=2.21.0->tensorboard<2.16,>=2.15->tensorflow) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.10/dist-packages (from requests<3,>=2.21.0->tensorboard<2.16,>=2.15->tensorflow) (3.6)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.10/dist-packages (from requests<3,>=2.21.0->tensorboard<2.16,>=2.15->tensorflow) (2.0.7)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.10/dist-packages (from requests<3,>=2.21.0->tensorboard<2.16,>=2.15->tensorflow) (2024.2.2)
Requirement already satisfied: MarkupSafe>=2.1.1 in /usr/local/lib/python3.10/dist-packages (from werkzeug>=1.0.1->tensorboard<2.16,>=2.15->tensorflow) (2.1.5)
Requirement already satisfied: pyasn1<0.6.0,>=0.4.6 in /usr/local/lib/python3.10/dist-packages (from pyasn1-modules>=0.2.1->google-auth<3,>=1.6.3->tensorboard<2.16,>=2.15->tensorflow) (0.5.1)
Requirement already satisfied: oauthlib>=3.0.0 in /usr/local/lib/python3.10/dist-packages (from requests-oauthlib>=0.7.0->google-auth-oauthlib<2,>=0.5->tensorboard<2.16,>=2.15->tensorflow) (3.2.2)

In [1]:
import tensorflow as tf

In [2]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

In [3]:
df=pd.read_csv('/content/Churn_Modelling.csv')

In [4]:
df.head()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [5]:
df.shape

(10000, 14)

In [6]:
df.drop(columns=['RowNumber','CustomerId','Surname'],inplace=True)

In [7]:
df.head()

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [8]:
x=df.iloc[:,:-1]

In [9]:
x

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary
0,619,France,Female,42,2,0.00,1,1,1,101348.88
1,608,Spain,Female,41,1,83807.86,1,0,1,112542.58
2,502,France,Female,42,8,159660.80,3,1,0,113931.57
3,699,France,Female,39,1,0.00,2,0,0,93826.63
4,850,Spain,Female,43,2,125510.82,1,1,1,79084.10
...,...,...,...,...,...,...,...,...,...,...
9995,771,France,Male,39,5,0.00,2,1,0,96270.64
9996,516,France,Male,35,10,57369.61,1,1,1,101699.77
9997,709,France,Female,36,7,0.00,1,0,1,42085.58
9998,772,Germany,Male,42,3,75075.31,2,1,0,92888.52
9999,792,France,Female,28,4,130142.79,1,1,0,38190.78

In [10]:
y=df.iloc[:,-1]

In [11]:
y

0       1
1       0
2       1
3       0
4       0
       ..
9995    0
9996    0
9997    1
9998    1
9999    0
Name: Exited, Length: 10000, dtype: int64

In [12]:
x.head()

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary
0,619,France,Female,42,2,0.00,1,1,1,101348.88
1,608,Spain,Female,41,1,83807.86,1,0,1,112542.58
2,502,France,Female,42,8,159660.80,3,1,0,113931.57
3,699,France,Female,39,1,0.00,2,0,0,93826.63
4,850,Spain,Female,43,2,125510.82,1,1,1,79084.10

In [13]:
x['Geography'].unique()

array(['France', 'Spain', 'Germany'], dtype=object)

In [14]:
from sklearn.preprocessing import OneHotEncoder

In [15]:

from sklearn.compose import ColumnTransformer

In [16]:
cat_col=x[['Geography','Gender']]

In [17]:
ohe=OneHotEncoder()

In [18]:
encoded_columns = ohe.fit_transform(cat_col)

In [19]:
encoded_df = pd.DataFrame(encoded_columns.toarray(), columns=ohe.get_feature_names_out(['Geography','Gender']))

In [20]:
encoded_df

,Geography_France,Geography_Germany,Geography_Spain,Gender_Female,Gender_Male
0,1.0,0.0,0.0,1.0,0.0
1,0.0,0.0,1.0,1.0,0.0
2,1.0,0.0,0.0,1.0,0.0
3,1.0,0.0,0.0,1.0,0.0
4,0.0,0.0,1.0,1.0,0.0
...,...,...,...,...,...
9995,1.0,0.0,0.0,0.0,1.0
9996,1.0,0.0,0.0,0.0,1.0
9997,1.0,0.0,0.0,1.0,0.0
9998,0.0,1.0,0.0,0.0,1.0
9999,1.0,0.0,0.0,1.0,0.0

In [21]:
x.drop(columns=['Geography','Gender'],inplace=True)

In [22]:
x=pd.concat([x,encoded_df],axis=1)

In [23]:
x.head()

,CreditScore,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Geography_France,Geography_Germany,Geography_Spain,Gender_Female,Gender_Male
0,619,42,2,0.00,1,1,1,101348.88,1.0,0.0,0.0,1.0,0.0
1,608,41,1,83807.86,1,0,1,112542.58,0.0,0.0,1.0,1.0,0.0
2,502,42,8,159660.80,3,1,0,113931.57,1.0,0.0,0.0,1.0,0.0
3,699,39,1,0.00,2,0,0,93826.63,1.0,0.0,0.0,1.0,0.0
4,850,43,2,125510.82,1,1,1,79084.10,0.0,0.0,1.0,1.0,0.0

In [24]:
from sklearn.model_selection import train_test_split

In [25]:
X_train,X_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [26]:
# feature scaling

In [27]:
from sklearn.preprocessing import StandardScaler

In [28]:
sc=StandardScaler()

In [29]:
X_train=sc.fit_transform(X_train)
X_test=sc.transform(X_test)

In [30]:
X_train

array([[ 0.35649971, -0.6557859 ,  0.34567966, ..., -0.57638802,
        -0.91324755,  0.91324755],
       [-0.20389777,  0.29493847, -0.3483691 , ..., -0.57638802,
        -0.91324755,  0.91324755],
       [-0.96147213, -1.41636539, -0.69539349, ...,  1.73494238,
        -0.91324755,  0.91324755],
       ...,
       [ 0.86500853, -0.08535128, -1.38944225, ..., -0.57638802,
         1.09499335, -1.09499335],
       [ 0.15932282,  0.3900109 ,  1.03972843, ..., -0.57638802,
        -0.91324755,  0.91324755],
       [ 0.47065475,  1.15059039, -1.38944225, ..., -0.57638802,
        -0.91324755,  0.91324755]])

In [31]:
# LETS CREATE ANN

In [32]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.layers import LeakyReLU,ELU,PReLU
from tensorflow.keras.layers import Dropout

In [40]:
#lets initialize ANN
classifier=Sequential()

In [41]:
#adding the input layer
classifier.add(Dense(units=11,activation='relu'))

In [42]:
#adding the first hidden layer
classifier.add(Dense(units=7,activation='relu'))
#adding dropout layer
#classifier.add(Dropout(0.2))

In [43]:
#adding second hidden layer
classifier.add(Dense(units=6,activation='relu'))

In [44]:
#adding output layer
classifier.add(Dense(units=1,activation='sigmoid'))

In [45]:
classifier.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])

In [46]:
model_history=classifier.fit(X_train,y_train,validation_split=0.33,batch_size=10,epochs=10)

Epoch 1/10
536/536 [==============================] - 4s 6ms/step - loss: 0.4925 - accuracy: 0.7947 - val_loss: 0.4498 - val_accuracy: 0.7910
Epoch 2/10
536/536 [==============================] - 2s 5ms/step - loss: 0.4323 - accuracy: 0.8015 - val_loss: 0.4298 - val_accuracy: 0.8042
Epoch 3/10
536/536 [==============================] - 2s 5ms/step - loss: 0.4128 - accuracy: 0.8190 - val_loss: 0.4193 - val_accuracy: 0.8190
Epoch 4/10
536/536 [==============================] - 2s 4ms/step - loss: 0.3962 - accuracy: 0.8294 - val_loss: 0.4052 - val_accuracy: 0.8281
Epoch 5/10
536/536 [==============================] - 3s 6ms/step - loss: 0.3807 - accuracy: 0.8410 - val_loss: 0.3942 - val_accuracy: 0.8319
Epoch 6/10
536/536 [==============================] - 3s 5ms/step - loss: 0.3686 - accuracy: 0.8475 - val_loss: 0.3877 - val_accuracy: 0.8334
Epoch 7/10
536/536 [==============================] - 2s 5ms/step - loss: 0.3566 - accuracy: 0.8554 - val_loss: 0.3759 - val_accuracy: 0.8451
Epoch 8/10
536/536 [==============================] - 2s 4ms/step - loss: 0.3499 - accuracy: 0.8569 - val_loss: 0.3672 - val_accuracy: 0.8501
Epoch 9/10
536/536 [==============================] - 2s 4ms/step - loss: 0.3426 - accuracy: 0.8602 - val_loss: 0.3678 - val_accuracy: 0.8497
Epoch 10/10
536/536 [==============================] - 4s 7ms/step - loss: 0.3396 - accuracy: 0.8617 - val_loss: 0.3657 - val_accuracy: 0.8523

In [47]:
model_history.history.keys()

dict_keys(['loss', 'accuracy', 'val_loss', 'val_accuracy'])

In [48]:
y_pred=classifier.predict(X_test)
y_pred=(y_pred>=0.5)

63/63 [==============================] - 0s 2ms/step

In [49]:
#make confusion metrics
from sklearn.metrics import confusion_matrix,accuracy_score

In [50]:
cm=confusion_matrix(y_test,y_pred)

In [51]:
cm

array([[1541,   66],
       [ 227,  166]])

In [52]:
accuracy_score(y_test,y_pred)

0.8535

In [53]:
classifier.get_weights()

[array([[ 3.96282412e-02,  6.94216266e-02,  8.04522187e-02,
         -1.26869142e-01,  1.84338585e-01,  2.33889252e-01,
         -1.52067348e-01, -9.12163779e-02,  3.28067690e-02,
          1.51238754e-01,  7.54321069e-02],
        [-9.27924335e-01, -5.26310444e-01, -4.88991439e-01,
          4.09164250e-01, -6.03793442e-01, -7.90357411e-01,
          6.06055968e-02, -7.00777411e-01, -1.01133576e-02,
          7.49451444e-02,  2.66734511e-01],
        [ 1.04242876e-01,  1.93306580e-01,  1.44272998e-01,
         -3.49377722e-01, -1.38843328e-01,  4.32479158e-02,
          5.74396014e-01,  2.43784145e-01, -4.68072206e-01,
         -2.53457278e-01,  1.11902006e-01],
        [ 1.98560759e-01,  4.06162053e-01,  8.77094865e-02,
         -2.02454198e-02, -3.16998869e-01, -1.55423015e-01,
         -2.04817250e-01,  2.42945418e-01,  2.09079355e-01,
          2.61787236e-01,  2.14525819e-01],
        [ 7.80851766e-02,  1.22120488e+00,  1.41687691e-01,
          9.70721006e-01,  1.40829846e-01,  7.09151626e-02,
          5.01156569e-01,  2.66373694e-01,  4.65963334e-01,
         -9.66712981e-02,  1.84643209e-01],
        [-4.06147987e-02, -1.63028583e-01, -3.55713785e-01,
         -1.45538032e-01, -1.67702958e-01, -1.77230448e-01,
          2.99588025e-01,  1.24462232e-01,  2.22871572e-01,
          2.07192838e-01,  9.17858258e-02],
        [-1.14808090e-01,  2.45924383e-01,  1.15397491e-01,
          4.36287284e-01,  4.06086817e-02, -1.02067225e-01,
          1.02995299e-01, -2.33849451e-01,  3.26538607e-02,
          5.36321402e-01,  7.75786638e-01],
        [ 4.54535931e-02,  1.19175516e-01,  3.85246649e-02,
         -2.99007863e-01,  2.33962908e-01,  8.17767717e-03,
         -2.19369218e-01, -1.71760187e-01,  3.74492221e-02,
          2.16523409e-01,  2.34354988e-01],
        [-2.66654551e-01,  2.27109507e-01,  6.90452522e-04,
          4.94946092e-02,  8.92432779e-02,  2.85048723e-01,
          3.32587957e-01, -2.02623636e-01, -7.87125975e-02,
          4.04168308e-01,  1.00075729e-01],
        [-3.72559935e-01, -4.14161325e-01, -3.60205561e-01,
         -5.81669947e-03,  1.65256158e-01, -1.56666294e-01,
         -6.39484882e-01, -3.15390289e-01,  5.79156913e-04,
          3.63653958e-01, -1.42421126e-01],
        [-2.17803344e-01,  2.12547883e-01,  3.26885357e-02,
          2.55244747e-02,  2.31158018e-01, -7.06727862e-01,
          4.57886606e-01, -6.66154176e-02, -2.92918503e-01,
         -4.91405502e-02,  1.89582452e-01],
        [ 5.74645162e-01, -9.48357955e-02, -1.80145055e-01,
          4.80557948e-01, -4.85800914e-02, -3.40326540e-02,
          1.58849955e-01, -2.33540729e-01, -8.25213864e-02,
          2.07551330e-01, -7.60388151e-02],
        [-5.25889814e-01,  1.84119050e-03,  5.34913421e-01,
          6.87740892e-02,  3.18065882e-01,  2.13881165e-01,
         -1.79958314e-01,  6.65063918e-01,  3.49986732e-01,
          3.33487205e-02,  2.61983097e-01]], dtype=float32),
 array([ 0.06847714, -0.3006311 ,  0.16031504,  0.54317486,  0.43130365,
         0.2603093 ,  0.05618187,  0.30516556,  0.26099625,  0.04365454,
         0.13724223], dtype=float32),
 array([[ 0.48005638, -0.05097695,  0.53609806,  0.54357976, -0.5980877 ,
         -0.55090606,  0.5820992 ],
        [-0.32104668,  0.81287634, -0.02187413, -1.0100341 ,  0.5106073 ,
          0.8171931 ,  0.20554234],
        [ 0.16101679,  0.2008953 ,  0.5827238 ,  0.02261061, -0.2656622 ,
         -0.18398203, -0.05164075],
        [ 0.71500343,  0.05872072,  0.25560808, -0.82752806,  0.40738824,
          0.0714706 , -0.42804357],
        [ 0.14444183, -0.49623787, -0.04936816, -0.13362674, -0.6872271 ,
         -0.24833268,  0.3810365 ],
        [ 0.01317275, -0.32417515,  0.10761756,  0.1537485 , -0.21667829,
         -0.15261045,  0.47422963],
        [ 0.08534275,  0.33697888,  0.614382  ,  0.06900073, -0.28726038,
         -0.01346215, -0.0091553 ],
        [ 0.18773311, -0.4888738 ,  0.8147236 ,  0.38941762,  0.15558773,
         -0.31932712,  0.80961215],
        [ 0.42323482,  0.54990786,  0.11367235, -0.32807592,  0.01036813,
          0.37089422,  0.4968938 ],
        [-0.14240713, -0.6417914 ,  0.36477184, -0.4749986 ,  0.22100079,
         -0.09305368, -0.07889234],
        [ 0.2958687 , -0.19515255,  0.20575462,  0.30914244, -0.330854  ,
         -0.329164  ,  0.36093706]], dtype=float32),
 array([-0.07268725, -0.02771365,  0.04264886,  0.20320508,  0.21852471,
         0.2743529 , -0.00779805], dtype=float32),
 array([[-0.57162917,  0.31137362,  0.33783832,  0.38863352, -0.14139932,
          0.8495849 ],
        [ 0.04390894,  0.64138377, -0.1099657 , -0.7469738 , -0.0566288 ,
         -0.641675  ],
        [ 0.13640149,  0.21372652,  0.26826108,  0.6264784 ,  0.0370749 ,
          0.42461815],
        [ 0.08865967, -0.17017984, -0.67679375,  0.12772243,  0.37345085,
         -0.36903533],
        [ 0.7470238 ,  0.7809001 , -0.5079048 ,  0.34272665, -0.41941252,
         -0.0651444 ],
        [-0.04153699,  1.4528661 , -0.9886558 , -0.93442893,  0.11780959,
         -0.75808907],
        [-0.35166556,  0.62686366,  0.7829856 ,  0.28261158, -0.47577915,
         -0.07872178]], dtype=float32),
 array([ 0.56038964,  0.28112683,  0.04554688, -0.00164892, -0.09519719,
        -0.01928968], dtype=float32),
 array([[ 1.3643905 ],
        [ 0.37882966],
        [-0.66694474],
        [-0.3562505 ],
        [-0.82623595],
        [-0.86183566]], dtype=float32),
 array([0.22622952], dtype=float32)]